language: python
python:
  - 3.6
  - 3.5
  - 3.4
#  - 2.7

install:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
script:
  - pipenv run py.test tests --vcr-record-mode=none
  # Run tests against live API, but only once per CI build.
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pipenv run py.test tests --vcr-record-mode=all; fi
